In [1]:
import pandas as pd

def p1(x):
    return x.quantile(0.01)
def p5(x):
    return x.quantile(0.05)
def p10(x):
    return x.quantile(0.10)
def p25(x):
    return x.quantile(0.25)
def p50(x):
    return x.quantile(0.50)
def p75(x):
    return x.quantile(0.75)
def p90(x):
    return x.quantile(0.90)
def p95(x):
    return x.quantile(0.95)
def p99(x):
    return x.quantile(0.99)

In [2]:
dreams_clean=pd.read_csv("../data/dreams_clean.csv",delimiter=";",encoding="latin-1")

In [3]:
dreams_clean

,code,note,description,words,group_id
0,1,1957,"The one at the Meads's house, where it's bigge...",154.0,1
1,2,8/11/67,I'm at a family reunion in a large fine house ...,248.0,1
2,3,8/1/85,I watch a plane fly past and shortly realize i...,303.0,1
3,4,1985?,Me pulling the green leaves and berries off so...,468.0,1
4,5,1985?,I'm in a room that reminds me of (but definite...,561.0,1
...,...,...,...,...,...
43221,85,"F, age 18",The dream was about me and my boyfriend going ...,138.0,89
43222,86,"F, age 18",Two weeks ago this guy asked me to Senior Ball...,96.0,89
43223,87,"F, age 18",My boyfriend just broke up with me so he was o...,139.0,89
43224,88,"F, age 18",I was in my backyard and I was flying. I would...,104.0,89
43225,89,"F, age 18",I felt scared. I was pregnant in my dream. The...,92.0,89

In [4]:
dreams_clean["group"].unique()

KeyError: 'group'

## Grupos de sueÃ±os pre-seleccionados

In [6]:
group_list=[
"Chuck: a physical scientist",
"Kenneth",
"Melvin (Melora's husband)",
"Miami Home-Lab: Home",
"Miami Home-Lab: Lab",
"The Natural Scientist",
"Norman: a child molester",
"Pegasus: a factory worker",
"Phil 2: late 20s",
"Phil 3: retirement",
"The Physiologist",
"Robert Bosnak: A dream analyst",
'Vietnam Vet: 1970-2008 war dreams',
'Vietnam Vet: 2015 dreams', 
'Vietnam Vet: 2016-17 dreams']

In [7]:
dreams_groups=dreams_clean[dreams_clean["group"].isin(group_list)]

## Cantidad de sueÃ±os y palabras sin ningun filtro

In [16]:
words=dreams_groups[["group","words"]].groupby(['group']).agg({'group':['size'],'words':['mean',p1,p5,p10,p25,p50,p75,p90,p95,p99]})
words.columns = ["_".join(x) for x in words.columns.ravel()]
print('\033[1m'+"CANTIDAD TOTAL DE SUEÃ‘OS: ",words.iloc[:,0].sum())
words

CANTIDAD TOTAL DE SUEÃ‘OS:  6457

,group_size,words_mean,words_p1,words_p5,words_p10,words_p25,words_p50,words_p75,words_p90,words_p95,words_p99
group,,,,,,,,,,,
Chuck: a physical scientist,75,167.173333,31.66,49.50,69.8,102.50,154.0,198.50,298.4,350.80,400.82
Kenneth,2021,178.558634,20.00,31.00,43.0,71.00,133.0,234.00,373.0,479.00,744.40
Melvin (Melora's husband),128,530.835938,61.40,87.70,122.7,251.00,425.5,786.75,1060.0,1223.50,1406.55
Miami Home-Lab: Home,171,241.818713,26.40,36.50,54.0,81.50,131.0,237.50,526.0,962.50,1576.80
Miami Home-Lab: Lab,274,352.003650,31.00,54.30,76.9,126.00,223.0,401.75,845.6,1071.50,1648.97
Norman: a child molester,1235,41.570850,5.34,9.00,12.0,19.00,31.0,51.00,86.0,113.30,175.32
Pegasus: a factory worker,1093,124.362306,8.00,16.00,24.0,51.00,99.0,173.00,257.8,310.40,423.08
Phil 2: late 20s,220,187.940909,23.19,40.95,50.9,85.75,153.0,258.25,332.1,474.20,679.74
Phil 3: retirement,180,154.900000,31.53,39.85,50.9,79.75,130.5,203.25,281.5,344.75,503.54
Robert Bosnak: A dream analyst,53,147.320755,10.04,24.60,27.2,60.00,103.0,161.00,289.2,478.00,706.36
The Natural Scientist,234,145.730769,14.00,26.65,34.3,56.25,106.5,181.00,327.2,438.60,659.51
The Physiologist,86,105.790698,18.85,26.00,27.5,51.00,85.5,132.50,210.0,277.75,298.95
Vietnam Vet: 1970-2008 war dreams,98,150.561224,40.97,47.70,64.7,88.00,135.0,188.25,266.8,310.50,403.91
Vietnam Vet: 2015 dreams,32,113.062500,28.89,42.00,43.2,86.75,110.5,136.50,207.8,215.35,221.83
Vietnam Vet: 2016-17 dreams,557,134.580994,26.62,42.10,54.2,81.00,121.0,173.50,227.0,268.50,367.04

## Si filtramos con 50 palabras

In [15]:
dreams_groups_n50=dreams_groups[dreams_groups["words"]>50]
words_50=dreams_groups_n50[["group","words"]].groupby(['group']).agg({'group':['size'],'words':['mean',p1,p5,p10,p25,p50,p75,p90,p95,p99]})
words_50.columns = ["_".join(x) for x in words_50.columns.ravel()]
print('\033[1m'+"CANTIDAD TOTAL DE SUEÃ‘OS CON +50 PALABRAS: ",words_50.iloc[:,0].sum())
words_50

CANTIDAD TOTAL DE SUEÃ‘OS CON +50 PALABRAS:  4701

,group_size,words_mean,words_p1,words_p5,words_p10,words_p25,words_p50,words_p75,words_p90,words_p95,words_p99
group,,,,,,,,,,,
Chuck: a physical scientist,71,174.605634,58.70,70.0,74.0,110.00,157.0,208.50,302.0,356.00,403.10
Kenneth,1751,200.690463,52.00,58.0,66.0,94.50,154.0,258.00,396.0,496.50,764.50
Melvin (Melora's husband),127,534.708661,77.04,89.6,129.0,255.00,434.0,790.50,1061.0,1227.00,1406.90
Miami Home-Lab: Home,155,263.019355,54.54,60.0,66.4,99.00,147.0,260.50,604.8,1001.40,1600.16
Miami Home-Lab: Lab,262,366.374046,55.00,75.0,91.0,144.50,232.5,444.75,879.5,1077.50,1662.29
Norman: a child molester,319,87.257053,51.00,52.0,53.0,61.00,76.0,102.50,133.4,153.00,221.02
Pegasus: a factory worker,824,155.675971,52.00,58.0,64.0,88.00,129.0,197.00,279.7,329.85,433.85
Phil 2: late 20s,198,204.772727,53.97,69.0,76.4,102.25,169.5,267.50,341.0,500.45,691.23
Phil 3: retirement,162,167.796296,54.61,61.0,66.0,93.00,143.5,214.25,286.0,358.25,516.86
Robert Bosnak: A dream analyst,41,182.317073,55.20,62.0,68.0,88.00,126.0,213.00,356.0,535.00,716.20
The Natural Scientist,186,174.580645,51.00,56.0,59.5,78.50,133.5,209.75,350.5,460.00,728.15
The Physiologist,66,128.712121,51.00,53.5,60.0,75.00,108.5,153.00,258.0,283.25,313.55
Vietnam Vet: 1970-2008 war dreams,89,161.191011,64.88,68.4,79.6,101.00,145.0,195.00,272.0,324.00,412.64
Vietnam Vet: 2015 dreams,27,126.777778,57.42,73.0,85.4,102.00,113.0,141.50,214.0,216.10,222.18
Vietnam Vet: 2016-17 dreams,423,143.640662,54.00,61.0,69.2,96.00,127.0,179.00,230.8,278.50,370.24

## Si filtramos con 75 palabras

In [17]:
dreams_groups_n75=dreams_groups[dreams_groups["words"]>75]
words_75=dreams_groups_n75[["group","words"]].groupby(['group']).agg({'group':['size'],'words':['mean',p1,p5,p10,p25,p50,p75,p90,p95,p99]})
words_50.columns = ["_".join(x) for x in words_50.columns.ravel()]
print('\033[1m'+"CANTIDAD TOTAL DE SUEÃ‘OS CON +75 PALABRAS: ",words_75.iloc[:,0].sum())
words_75

CANTIDAD TOTAL DE SUEÃ‘OS CON +75 PALABRAS:  3909

                                  group       words                       \
                                   size        mean     p1     p5    p10
group
Chuck: a physical scientist          63  188.253968  81.00  94.40  101.6
Kenneth                            1483  225.730951  76.00  82.00   91.0
Melvin (Melora's husband)           126  538.507937  80.75  91.75  135.5
Miami Home-Lab: Home                134  294.462687  78.33  83.30   90.6
Miami Home-Lab: Lab                 247  384.744939  80.00  91.00  112.2
Norman: a child molester            161  112.987578  76.00  77.00   78.0
Pegasus: a factory worker           684  174.720760  77.00  83.15   89.0
Phil 2: late 20s                    178  220.455056  78.00  83.85   91.4
Phil 3: retirement                  141  183.666667  78.00  80.00   89.0
Robert Bosnak: A dream analyst       33  210.575758  79.88  87.20   90.4
The Natural Scientist               144  207.493056  76.43  84.30   93.0
The Physiologist                     48  153.500000  80.00  83.35   85.7
Vietnam Vet: 1970-2008 war dreams    82  169.268293  77.81  82.00   88.0
Vietnam Vet: 2015 dreams             25  132.000000  82.16  90.00   96.4
Vietnam Vet: 2016-17 dreams         360  157.483333  77.59  85.00   93.0

                                                                           \
                                      p25    p50     p75     p90      p95
group
Chuck: a physical scientist        128.50  168.0  221.00   307.6   366.40
Kenneth                            119.00  182.0  278.00   418.0   530.60
Melvin (Melora's husband)          258.50  435.0  794.25  1062.0  1230.50
Miami Home-Lab: Home               115.00  180.0  308.00   625.8  1053.55
Miami Home-Lab: Lab                156.00  246.0  463.50   923.2  1103.90
Norman: a child molester            87.00  102.0  129.00   153.0   194.00
Pegasus: a factory worker          105.00  149.0  216.25   296.7   347.40
Phil 2: late 20s                   120.75  187.5  282.75   398.5   523.30
Phil 3: retirement                 109.00  155.0  222.00   295.0   372.00
Robert Bosnak: A dream analyst     118.00  143.0  221.00   423.2   587.80
The Natural Scientist              112.75  156.0  245.25   368.8   504.25
The Physiologist                   101.50  128.0  194.25   277.3   285.65
Vietnam Vet: 1970-2008 war dreams  106.25  152.0  207.25   275.5   334.50
Vietnam Vet: 2015 dreams           104.00  116.0  142.00   214.0   216.40
Vietnam Vet: 2016-17 dreams        110.75  137.0  188.25   245.0   284.05


                                       p99
group
Chuck: a physical scientist         407.66
Kenneth                             786.72
Melvin (Melora's husband)          1407.25
Miami Home-Lab: Home               1630.82
Miami Home-Lab: Lab                1678.94
Norman: a child molester            227.20
Pegasus: a factory worker           446.23
Phil 2: late 20s                    699.43
Phil 3: retirement                  532.40
Robert Bosnak: A dream analyst      722.76
The Natural Scientist               778.97
The Physiologist                    326.69
Vietnam Vet: 1970-2008 war dreams   419.43
Vietnam Vet: 2015 dreams            222.32
Vietnam Vet: 2016-17 dreams         372.41